[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "2W4wkSy2QJ9SczvUfyPNYDLgqpEZ5WVktpEXVfTzBVJP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
