[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
contract = "J1AmhNEsVQukD8cvRh7zRD9jh56QocsoGCBrfTvTmAus"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
