[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/contract"
]
exclude = [
    "programs/mock_ika",
    "programs/mock_encrypt"
]

[programs.devnet]
contract = "fyXZDXLNmygJ7FeXYW8uae4V1kiZJojsS9YoRE2VW1Q"
mock_ika = "CXHt5JcKMshPiW7HJUqyRnyUugQTnoWN3mbWm92sGLMw"
mock_encrypt = "4ebfzWdKnrnGseuQpezXdG8yCdHqwQ1SSBHD3bWArND8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
pre-build = "NO_DNA=1 CARGO_NET_OFFLINE=true cargo build-sbf --manifest-path programs/mock_ika/Cargo.toml && NO_DNA=1 CARGO_NET_OFFLINE=true cargo build-sbf --manifest-path programs/mock_encrypt/Cargo.toml"
