/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkspacePreviewRouteImport } from './routes/app.workspace-preview'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppProofRouteImport } from './routes/app.proof'
import { Route as AppGatePreviewRouteImport } from './routes/app.gate-preview'
import { Route as AppGateRouteImport } from './routes/app.gate'
import { Route as AppFundsRouteImport } from './routes/app.funds'
import { Route as AppBridgeRouteImport } from './routes/app.bridge'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacePreviewRoute = AppWorkspacePreviewRouteImport.update({
  id: '/workspace-preview',
  path: '/workspace-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppProofRoute = AppProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => AppRoute,
} as any)
const AppGatePreviewRoute = AppGatePreviewRouteImport.update({
  id: '/gate-preview',
  path: '/gate-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppGateRoute = AppGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AppRoute,
} as any)
const AppFundsRoute = AppFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppRoute,
} as any)
const AppBridgeRoute = AppBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/app/bridge': typeof AppBridgeRoute
  '/app/funds': typeof AppFundsRoute
  '/app/gate': typeof AppGateRoute
  '/app/gate-preview': typeof AppGatePreviewRoute
  '/app/proof': typeof AppProofRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/workspace-preview': typeof AppWorkspacePreviewRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/bridge': typeof AppBridgeRoute
  '/app/funds': typeof AppFundsRoute
  '/app/gate': typeof AppGateRoute
  '/app/gate-preview': typeof AppGatePreviewRoute
  '/app/proof': typeof AppProofRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/workspace-preview': typeof AppWorkspacePreviewRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/app/bridge': typeof AppBridgeRoute
  '/app/funds': typeof AppFundsRoute
  '/app/gate': typeof AppGateRoute
  '/app/gate-preview': typeof AppGatePreviewRoute
  '/app/proof': typeof AppProofRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/workspace-preview': typeof AppWorkspacePreviewRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/app/bridge'
    | '/app/funds'
    | '/app/gate'
    | '/app/gate-preview'
    | '/app/proof'
    | '/app/workspace'
    | '/app/workspace-preview'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app/bridge'
    | '/app/funds'
    | '/app/gate'
    | '/app/gate-preview'
    | '/app/proof'
    | '/app/workspace'
    | '/app/workspace-preview'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/app/bridge'
    | '/app/funds'
    | '/app/gate'
    | '/app/gate-preview'
    | '/app/proof'
    | '/app/workspace'
    | '/app/workspace-preview'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace-preview': {
      id: '/app/workspace-preview'
      path: '/workspace-preview'
      fullPath: '/app/workspace-preview'
      preLoaderRoute: typeof AppWorkspacePreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proof': {
      id: '/app/proof'
      path: '/proof'
      fullPath: '/app/proof'
      preLoaderRoute: typeof AppProofRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gate-preview': {
      id: '/app/gate-preview'
      path: '/gate-preview'
      fullPath: '/app/gate-preview'
      preLoaderRoute: typeof AppGatePreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gate': {
      id: '/app/gate'
      path: '/gate'
      fullPath: '/app/gate'
      preLoaderRoute: typeof AppGateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funds': {
      id: '/app/funds'
      path: '/funds'
      fullPath: '/app/funds'
      preLoaderRoute: typeof AppFundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bridge': {
      id: '/app/bridge'
      path: '/bridge'
      fullPath: '/app/bridge'
      preLoaderRoute: typeof AppBridgeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBridgeRoute: typeof AppBridgeRoute
  AppFundsRoute: typeof AppFundsRoute
  AppGateRoute: typeof AppGateRoute
  AppGatePreviewRoute: typeof AppGatePreviewRoute
  AppProofRoute: typeof AppProofRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppWorkspacePreviewRoute: typeof AppWorkspacePreviewRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBridgeRoute: AppBridgeRoute,
  AppFundsRoute: AppFundsRoute,
  AppGateRoute: AppGateRoute,
  AppGatePreviewRoute: AppGatePreviewRoute,
  AppProofRoute: AppProofRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppWorkspacePreviewRoute: AppWorkspacePreviewRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
